### ISSUE TITLE
Battery percentage shows too many decimals

### ISSUE THREAD

**Issue by burritosoftware** [EnderdracheLP/ClockMod#5]
![043B7361-499B-4DCF-8DD2-5BF4567861B9](https://user-images.githubusercontent.com/37681398/107186112-860ee280-6998-11eb-828c-2497f15af46d.jpeg)  
When a battery percentage is nearing the next percentage or just going below a certain percentage, a long string of decimals show.  
  
This should be fixed by only showing the whole number and hiding the decimal.

**Comment by EnderdracheLP** [comment]
Just encountered that myself today, will work on a fix, seems to be an issue with floating point numbers, man I hate working with them.
